server:
  port: 8000

spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

  data:
    mongodb:
      primary:
        uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}

datasource:
  javabase:
    jdbc-url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_DATABASE}?zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    connection-timeout: ${DB_CONNECTION_TIMEOUT:10000}
    idle-timeout: ${DB_IDLE_TIMEOUT:1800000}
    max-lifetime: ${DB_MAX_LIFETIME:28000000}
    maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
    minimum-idle: ${DB_MIN_POOL_SIZE:1}
    pool-name: ${DB_POOL_NAME:JavaBase-HikariPool}

